version: '3.9'

services:
    app:
        stdin_open: true
        build:
            context: ../
            dockerfile: ./.devcontainer/Dockerfile
            args:
                TAG: '19-alpine3.15'
        ports:
            - '3000:3000'
        volumes:
            - ../product:/app/product
            - /app/product/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
